// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Lunaris config value passed from Rust to TypeScript.
 *
 * The TypeScript shell reads config via Tauri commands; this is the
 * response type.
 */
export type ConfigValue = { "kind": "String", "value": string } | { "kind": "Int", "value": bigint } | { "kind": "Float", "value": number } | { "kind": "Bool", "value": boolean } | { "kind": "Missing" };
