// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single row returned by a Knowledge Graph query.
 *
 * Fields are serialized as a JSON string to avoid serde_json::Value
 * not implementing ts_rs::TS. The TypeScript side parses this with JSON.parse().
 */
export type GraphRow = { 
/**
 * JSON-encoded map of field name to value.
 */
fields_json: string, };
