// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphRow } from "./GraphRow";

/**
 * The result of a Knowledge Graph query.
 */
export type GraphQueryResult = { rows: Array<GraphRow>, };
