// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single event emitted over the Lunaris Event Bus.
 *
 * Sent from Rust to TypeScript when the shell needs to react to system events.
 */
export type ShellEvent = { 
/**
 * UUID v7.
 */
id: string, 
/**
 * Event type in `category.action` format, e.g. `window.focused`.
 */
event_type: string, 
/**
 * Unix timestamp in microseconds.
 */
timestamp: bigint, 
/**
 * Emitting component, e.g. `compositor` or `ebpf`.
 */
source: string, 
/**
 * Session the event belongs to.
 */
session_id: string, };
