// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Surface token colors loaded from `theme.toml`.
 *
 * Passed to the WebView at startup so the shell can set CSS custom properties.
 */
export type SurfaceTokens = { 
/**
 * Shell background (panel, launcher). Usually dark in Panda theme.
 */
bg_shell: string, 
/**
 * App window background. Usually light in Panda theme.
 */
bg_app: string, 
/**
 * Card/panel backgrounds inside apps.
 */
bg_card: string, 
/**
 * Overlay backgrounds (modals, popovers).
 */
bg_overlay: string, 
/**
 * Input field backgrounds.
 */
bg_input: string, 
/**
 * Primary text color on shell surfaces.
 */
fg_shell: string, 
/**
 * Primary text color on app surfaces.
 */
fg_app: string, 
/**
 * Accent color for interactive elements and focus rings.
 */
accent: string, 
/**
 * Border color for separators and input outlines.
 */
border: string, };
